### ISSUE TITLE
pip install gcloud is broken :(

### ISSUE THREAD

**Issue by jgeewax** [GoogleCloudPlatform/gcloud-python#1304]
Looks like installing gives some proto errors on fresh Ubuntu 15.10.... can we fix ASAP?

```sh
jj@jjg-home:~$ virtualenv test-env
New python executable in test-env/bin/python
Installing setuptools, pip, wheel...done.
jj@jjg-home:~$ source test-env/bin/activate
(test-env)jj@jjg-home:~$ pip install gcloud
Collecting gcloud
  Downloading gcloud-0.8.0.tar.gz (244kB)
    100% |████████████████████████████████| 245kB 1.5MB/s 
Collecting google-apitools (from gcloud)
  Downloading google_apitools-0.4.13-py2-none-any.whl (122kB)
    100% |████████████████████████████████| 122kB 1.1MB/s 
Collecting httplib2>=0.9.1 (from gcloud)
  Downloading httplib2-0.9.2.tar.gz (205kB)
    100% |████████████████████████████████| 208kB 1.3MB/s 
Collecting oauth2client>=1.4.6 (from gcloud)
  Downloading oauth2client-1.5.2.tar.gz (56kB)
    100% |████████████████████████████████| 57kB 2.8MB/s 
Collecting protobuf>=3.0.0a3 (from gcloud)
  Downloading protobuf-3.0.0b1.post1.tar.gz (200kB)
    100% |████████████████████████████████| 200kB 1.4MB/s 
Collecting pycrypto (from gcloud)
  Downloading pycrypto-2.6.1.tar.gz (446kB)
    100% |████████████████████████████████| 446kB 1.0MB/s 
Collecting six (from gcloud)
  Downloading six-1.10.0-py2.py3-none-any.whl
Collecting protorpc>=0.9.1 (from google-apitools->gcloud)
  Downloading protorpc-0.11.1-py2-none-any.whl (134kB)
    100% |████████████████████████████████| 135kB 1.6MB/s 
Collecting pyasn1>=0.1.7 (from oauth2client>=1.4.6->gcloud)
  Downloading pyasn1-0.1.9-py2.py3-none-any.whl
Collecting pyasn1-modules>=0.0.5 (from oauth2client>=1.4.6->gcloud)
  Downloading pyasn1_modules-0.0.8-py2.py3-none-any.whl
Collecting rsa>=3.1.4 (from oauth2client>=1.4.6->gcloud)
  Downloading rsa-3.2.3-py2.py3-none-any.whl (44kB)
    100% |████████████████████████████████| 45kB 3.2MB/s 
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./test-env/lib/python2.7/site-packages (from protobuf>=3.0.0a3->gcloud)
Building wheels for collected packages: gcloud, httplib2, oauth2client, protobuf, pycrypto
  Running setup.py bdist_wheel for gcloud
  Stored in directory: /home/jj/.cache/pip/wheels/b6/68/f5/2793d54238f36f034c170e231252b7113a1410d6baef7ed203
  Running setup.py bdist_wheel for httplib2
  Stored in directory: /home/jj/.cache/pip/wheels/e1/a3/05/e66aad1380335ee0a823c8f1b9006efa577236a24b3cb1eade
  Running setup.py bdist_wheel for oauth2client
  Stored in directory: /home/jj/.cache/pip/wheels/79/9e/56/e82aa05430ac46bd675b90e030d09d567cd29a524ff9ce1a67
  Running setup.py bdist_wheel for protobuf
  Complete output from command /home/jj/test-env/bin/python -c "import setuptools;__file__='/tmp/pip-build-GzHddN/protobuf/setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" bdist_wheel -d /tmp/tmp_fhLv_pip-wheel-:
  running bdist_wheel
  running build
  running build_py
  protoc is not installed nor found in ../src.  Please compile it or install the binary package.
  Generating google/protobuf/pyext/python_pb2.py...
  
  ----------------------------------------
  Failed building wheel for protobuf
  Running setup.py bdist_wheel for pycrypto
  Stored in directory: /home/jj/.cache/pip/wheels/96/b0/e6/03e439d41cb2592b5c4c9c77873761d6cbd417b332076680cd
Successfully built gcloud httplib2 oauth2client pycrypto
Failed to build protobuf
Installing collected packages: six, httplib2, pyasn1, pyasn1-modules, rsa, oauth2client, protorpc, google-apitools, protobuf, pycrypto, gcloud
  Running setup.py install for protobuf
    Complete output from command /home/jj/test-env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-GzHddN/protobuf/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KIaR6V-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jj/test-env/include/site/python2.7/protobuf:
    running install
    running build
    running build_py
    protoc is not installed nor found in ../src.  Please compile it or install the binary package.
    Generating google/protobuf/pyext/python_pb2.py...
    
    ----------------------------------------
Command "/home/jj/test-env/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-GzHddN/protobuf/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-KIaR6V-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/jj/test-env/include/site/python2.7/protobuf" failed with error code 255 in /tmp/pip-build-GzHddN/protobuf
(test-env)jj@jjg-home:~$ 
```

**Comment by dhermes** [comment]
I filed https://github.com/google/protobuf/issues/1056 yesterday. The protobuf folks made a busted release, no idea why.

**Comment by dhermes** [comment]
Updated `setup.py` in https://github.com/GoogleCloudPlatform/gcloud-python/commit/d11980f86eeed1ba96c42ef5fdbd7fc8c37b1a6f to pin on `protobuf==3.0.0a3`.

You can get it installed by installing `protobuf` first and then installing our library:

```
pip install protobuf==3.0.0a3
pip install gcloud
```

We need to cut a release soon anyhow, but you should poke someone who works on `protobuf` to look at that issue.

**Comment by jgeewax** [comment]
Got it -- can we pin to `<= 3.0.0a3` in the meantime?

**Comment by jgeewax** [comment]
....aaand I just finished reading your whole comment. Ignore me :)

**Comment by dhermes** [comment]
Already updated `setup.py` (see above) but it doesn't change existing releases

**Comment by dhermes** [comment]
Haha ditto. Like phone tag

**Comment by jgeewax** [comment]
Got it -- sent a request to someone on the proto team who hopefully can help sort out https://github.com/google/protobuf/issues/1056

**Comment by dhermes** [comment]
This is fixed now.

**Comment by vijaypalmanit** [comment]
still not resolved for me, although i followed the same steps

**Comment by daspecster** [comment]
Glad to hear you got it working @vijaypalmanit.

Reference: https://github.com/GoogleCloudPlatform/google-cloud-python/issues/1570#issuecomment-283965389.
