### ISSUE TITLE
AppVeyor build is failing

### ISSUE THREAD

**Issue by dhermes** [GoogleCloudPlatform/gcloud-python#1863]
https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.422.master
https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.413.master

**Comment by daspecster** [comment]
I didn't know we had this, I'll get on this now.

**Comment by daspecster** [comment]
Can we add this to our merge checks?

**Comment by dhermes** [comment]
We intentionally didn't because it'd slow down merges

**Comment by daspecster** [comment]
@dhermes, if I could get on the email list for this and the docs when they fail that would be awesome.

Also, is there a way to flush the cache for appveyor?

**Comment by dhermes** [comment]
I took a quick peek at https://ci.appveyor.com/project/dhermes/gcloud-python/settings/permissions and can't figure out how to get you added. (No bandwidth to play around right now.) Can you find out how and help me click my way along?

**Comment by daspecster** [comment]
@dhermes, I think this will get you closer. 
http://www.appveyor.com/docs/team-setup

I think you can just go to https://ci.appveyor.com/team and add me as a _collaborator_ I believe.

I signed up for Appveyor with my github account so I should be in there somewhere.

**Comment by dhermes** [comment]
![screen shot 2016-06-16 at 3 49 46 pm](https://cloud.githubusercontent.com/assets/520669/16135664/05ac5d1e-33da-11e6-83cd-bc1aae321500.png)

**Comment by daspecster** [comment]
Oh sorry! My github account email it used was daspecster@gmail.com.  Not sure why it used that one over the one you have there though?  This might be my default one.

**Comment by dhermes** [comment]
OK added you

**Comment by daspecster** [comment]
Thanks! I don't see `gcloud-python` in my projects list but maybe it takes a bit.

**Comment by daspecster** [comment]
Looks like you might need to add permissions on a per project basis.
https://www.appveyor.com/docs/team-setup#permissions

> Permissions can be defined on project level and limit user access to that particular project. Project-level permission has three states: Allow, Deny and Inherit. "Inherit" means applying permissions defined on role level. Both "Allow" and "Deny" overrides permissions defined on role level.

**Comment by daspecster** [comment]
@dhermes, I can't restart the appveyor builds for some reason.
It looks like something might have gotten updated? Hard to tell from this comment.

https://github.com/grpc/grpc/issues/6939#issuecomment-226720519

**Comment by dhermes** [comment]
Permissions [seem fine][1] by default:

![screen shot 2016-06-17 at 10 36 17 am](https://cloud.githubusercontent.com/assets/520669/16159401/67415c76-3477-11e6-9591-c6d73beaa5b3.png)

[1]: https://ci.appveyor.com/project/dhermes/gcloud-python/settings/permissions

**Comment by daspecster** [comment]
I think it must be some kind of cross github permissions that's not letting
the projects show up in my projects list on appveyor.

I added the gcloud-python project manually and I'll try and build though.
https://ci.appveyor.com/project/daspecster/gcloud-python

On Fri, Jun 17, 2016 at 1:36 PM, Danny Hermes <notifications@github.com>
wrote:

> Permissions seem fine
> <https://ci.appveyor.com/project/dhermes/gcloud-python/settings/permissions>
> by default:
>
> [image: screen shot 2016-06-17 at 10 36 17 am]
> <https://cloud.githubusercontent.com/assets/520669/16159401/67415c76-3477-11e6-9591-c6d73beaa5b3.png>
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/1863#issuecomment-226832985>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AALvyCuHyW0akdMZ2W8mhXv9mRtgFJrHks5qMts6gaJpZM4I3hW4>
> .
>



-- 
Tom Schultz

**Comment by dhermes** [comment]
SGTM

**Comment by daspecster** [comment]
Still failing `grpcio` 
https://ci.appveyor.com/project/daspecster/gcloud-python

**Comment by daspecster** [comment]
@bjwatson, did you guys have any more ideas on this?

**Comment by tseaver** [comment]
*All* the environments are failing, not just the 2.7 ones (the only ones where `grpcio` is wired in).

**Comment by tseaver** [comment]
@daspecster, @dhermes Note that Danny's [Appveyor builds have been failing since the 0.14.1 release](https://ci.appveyor.com/project/dhermes/gcloud-python/history).

**Comment by daspecster** [comment]
I'll try and find a fix for this permissions issue. Looks like people run into that a little bit on appveyor.

**Comment by dhermes** [comment]
@daspecster I already added a fix for tempfiles in a previous commit. Trying to track now

**Comment by daspecster** [comment]
Awesome thanks @dhermes!

**Comment by dhermes** [comment]
#1413, #1222 and #1231 should be helpful

**Comment by bjwatson** [comment]
@daspecster No new ideas, apart from what's already been expressed in https://github.com/grpc/grpc/issues/6939. I did realize today that this issue applies to all recent versions of `grpcio`: `0.13.0`, `0.13.1`, and `0.14.0`.

Is this the first time we had a grpcio dependency in the `grpc-google-*` and `gax-google-*` packages that we are attempting to use on AppVeyor and ReadTheDocs?

**Comment by daspecster** [comment]
Yeah @tseaver mentioned above that it looks like it's been happening for a little while.

**Comment by tseaver** [comment]
@bjwatson We just merged #1815, making `grcpio` an unconditional dependency of `gcloud` on Python 2.7:  prior to the merge, users had to request installing the `gcloud[grpc]` extra dependency to get it.

@daspecster the other failures post 0.14.1 weren't related to `grpcio`.

**Comment by daspecster** [comment]
Ah ok, sorry I'm jumbling things up I guess.

On Friday, June 17, 2016, Tres Seaver <notifications@github.com> wrote:

> @bjwatson <https://github.com/bjwatson> We just merged #1815
> <https://github.com/GoogleCloudPlatform/gcloud-python/pull/1815>, making
> grcpio an unconditional dependency of gcloud on Python 2.7: prior to the
> merge, users had to request installing the gcloud[grpc] extra dependency
> to get it.
>
> @daspecster <https://github.com/daspecster> the other failures post
> 0.14.1 weren't related to grpcio.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/GoogleCloudPlatform/gcloud-python/issues/1863#issuecomment-226909849>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AALvyNFu5fnZFMXRaE54LshLQ46iBztPks5qMzqdgaJpZM4I3hW4>
> .
>


-- 
Tom Schultz

**Comment by dhermes** [comment]
@daspecster It's still failing: https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.428.master

**Comment by daspecster** [comment]
Is there a way to get around the `grpcio` issue that you know of?

**Comment by tseaver** [comment]
@daspecster If Appveyor sets a known environment variable, we could use it to avoid adding the `GRPC_EXTRAS` requirements to `install_requires`.

**Comment by daspecster** [comment]
I think it sets an `APPVEYOR` envar to true (https://www.appveyor.com/docs/environment-variables).

**Comment by dhermes** [comment]
So `grpcio` doesn't work on Windows? Isn't that a huge problem @jgeewax?

**Comment by tseaver** [comment]
@dhermes it appears to be an oddity with [installation through a dependency](https://github.com/grpc/grpc/issues/6939).  Maybe we could work around it by pre-installing `grpcio` under Appveyor?

**Comment by bjwatson** [comment]
Is this issue fixed, or is it still outstanding? I saw that https://github.com/grpc/grpc/issues/6939 was closed and will be fixed in 0.15.0.

**Comment by daspecster** [comment]
@bjwatson, I don't think 0.15.0 has been released yet to try it. Do you know when it might get released?

**Comment by bjwatson** [comment]
@daspecster I asked on the grpc ticket.

Does the force install patches that @tseaver merged provide a decent work-around for now?

**Comment by daspecster** [comment]
@bjwatson, I _think_ it just pulls from pypi.
https://github.com/GoogleCloudPlatform/gcloud-python/blob/master/appveyor.yml#L77

**Comment by daspecster** [comment]
Retrying build
https://ci.appveyor.com/project/daspecster/gcloud-python-pjqjn

**Comment by bjwatson** [comment]
@daspecster 0.15.0 will be probably be published sometime next week

**Comment by bjwatson** [comment]
That said, it looks like we will soon need to move away from egg-info dependencies, unless we have a really good reason for needing them: https://github.com/grpc/grpc/issues/6989

**Comment by dhermes** [comment]
Still getting b0rken emails:

https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.443.bigtable-v2
https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.447.logging-stdlib-handler-feature
https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.451.bigtable-v2
https://ci.appveyor.com/project/dhermes/gcloud-python/build/1.0.453.master

**Comment by bjwatson** [comment]
Looks like the errors have changed since the gRPC 0.15.0 release last night.

**Comment by tseaver** [comment]
Looks as though `protobuf` is not getting installed.  Since `gcloud` explicitly depends on it, I don't know how that can happen.

**Comment by bjwatson** [comment]
I don't know if this helps in this case, but last week I set up the [gax-python repo](https://github.com/googleapis/gax-python) to install (and cache) a protobuf installation for testing with proto messages (fix for https://github.com/GoogleCloudPlatform/gcloud-python/issues/1869):

https://github.com/googleapis/gax-python/pull/111/files

**Comment by bjwatson** [comment]
Also, I'm going to build some new versions of `google-gax`, `grpc-google-(pubsub|logging)`, and `gax-google-(pubsub|logging)` with `grpc 0.15.0` and `protobuf v3.0.0-beta-3.1` to see if that helps.

**Comment by bjwatson** [comment]
I have built and published `google-gax 0.12.2` and version `0.7.11` of the Pub/Sub and Logging packages

**Comment by dhermes** [comment]
This is fixed by a series of changes e.g. https://github.com/googleapis/gax-python/pull/120 and https://github.com/grpc/grpc/issues/7528
